-- +goose Up
-- +goose StatementBegin
create table if not exists public.restaurants (
    id int generated by default as identity primary key,
    name text not null,
    location geography(POINT) not null
)

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table public.restaurants;
-- +goose StatementEnd
