version: "3"
services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - ./data:/var/lib/postgresql/data
      # Move the init.sql script for "Creating the DB_NAME"
      # The Postgres Docker image is configured to run any .sql files in the
      # /docker-entrypoint-initdb.d directory when the container starts.
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
