-- Assuming our postgres database already enables PostGIS,

-- Create a restaurants table that has a location 
create table if not exists public.restaurants (
    id int generated by default as identity primary key,
    name text not null,
    location geography(POINT) not null
)
